export const LANGUAGES = [
 { name: "English", short: "en", flag: "🇺🇸" },
 { name: "Tiếng Việt", short: "vi", flag: "🇻🇳" },
 { name: "Español", short: "es", flag: "🇲🇽" },
 { name: "Bahasa Indonesia", short: "id", flag: "🇮🇩" },
 { name: "Português", short: "pt", flag: "🇧🇷" },
 { name: "Azərbaycan", short: "az", flag: "🇦🇿" },
 { name: "中文 (中国)", short: "zh", flag: "🇨🇳" },
 { name: "Français", short: "fr", flag: "🇫🇷" },
 { name: "日本語", short: "ja", flag: "🇯🇵" },
 { name: "Deutsch", short: "de", flag: "🇩🇪" },
 { name: "Italiano", short: "it", flag: "🇮🇹" },
 { name: "Polski", short: "pl", flag: "🇵🇱" },
 { name: "Русский", short: "ru", flag: "🇷🇺" },
 { name: "Türkçe", short: "tr", flag: "🇹🇷" },
 { name: "Română", short: "ro", flag: "🇷🇴" },
 { name: "العربية", short: "ar", flag: "🇸🇦" },
 { name: "اردو", short: "ur", flag: "🇵🇰" },
 { name: "فارسی", short: "fa", flag: "🇮🇷" },
 { name: "हिन्दी", short: "hi", flag: "🇮🇳" },
 { name: "नेपाली", short: "ne", flag: "🇳🇵" },
 { name: "বাংলা", short: "bn", flag: "🇧🇩" },
 { name: "עברית", short: "he", flag: "🇮🇱" },
 { name: "Українська", short: "uk", flag: "🇺🇦" },
 { name: "Afrikaans", short: "af", flag: "🇿🇦" },
 { name: "پشتو", short: "ps", flag: "🇦🇫" },
] as const;
