import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";

const geistSans = Geist({
 variable: "--font-geist-sans",
 subsets: ["latin"],
});

const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default async function RootLayout({
 children,
 params,
}: {
 children: React.ReactNode;
 params: Promise<{ locale: string }>;
}) {
 const { locale } = await params;

 if (!routing.locales.includes(locale as any)) {
  notFound();
 }
 const messages = await getMessages();

 return (
  <html lang={locale}>
   <body className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}>
    <NextIntlClientProvider messages={messages}>
     <Header />
     <main className="flex-stretch">{children}</main>
     <Footer />
    </NextIntlClientProvider>
   </body>
  </html>
 );
}
